---
backend:
  name: git-gateway
  branch: main

# file uploads
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Post"
    create: true
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: language
      value: en
    fields:
      - { label: "Language", name: "language" }
