---
backend:
  name: git-gateway
  branch: main

# file uploads
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://josephcomer.net
locale: en

collections:
  - name: "posts"
    label: "Post"
    create: true
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
